sudo: required

services:
- docker

env:
  global:
  - DOCKER_USERNAME=guillaumejacquenot
  - secure: "LfU9HawVzT2sAeXHAj5iAnqhmIQWqE3tg+pbar3URSUfBdCSymC8+3ecqK537o/dYQNYqGoF0Hg57j6MZqOoSse/rcWa263OHTvAYM5zXNSYjwcdKiF1gyZ4NvxYJF6nnvQFZBl6X0ZFONeTrx7XnshMLwS7xdrL2xm27EUbSJ4wlLYX5z6Ikuq7tMJsTuXURYaqZIfboiNCtWhZvkDPaMLnPsBSG05Oe/eVZMOVwwkBUo8oIBLr8vaORV3HBMXNdIORdGsddEvuTkP2+3uGhlZBywkPwFZMnYd1q6Tp8Oi3DhUi9N92kUPeSrzvi2ej3aJkX743MMdh0qGHYveC7mHQWU/68H3D3wPH4NDGdV1SqgY/nGmvnLyX6L9Wxi2ZqBlPkPnDY4f1J7vZXmVm/FMqCMMaK2DBi29gVWAMvSb/Qw4NdOYWdXR3tQ5n4x2KhYL5wXL5V7NF5PNJz1KuvVDanY3bsl2DTDvKuTF4Ak2vNY67DhuBo6xqGVYMgrspTgjjizz9chmVvnvioSy7xeHDZVdGwBpfyJSyf8Ge06YZdCEmNqaqngs+goIU7MfgIgmvFDR5plg+Ej4Syl/cBdNR/LaFUprJiVP432BaIUbJ4TDhErPXbeHAg1QVh303WU6PQ/gAjAn291zAZtIlzm/zqlBskk1D61nt0LoP2/s="

before_install:
- echo "Before install"

before_script:
- docker pull sirehna/base-image-debian8-gcc492-xdyn || true

script:
- docker build --pull --cache-from sirehna/base-image-debian8-gcc492-xdyn --tag sirehna/base-image-debian8-gcc492-xdyn .

after_script:
- docker images

after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then docker login -u $DOCKER_USERNAME -p
  $DOCKER_PASSWORD ; docker push sirehna/base-image-debian8-gcc492-xdyn ; fi

notifications:
  email: true
